[build]
command = "npm install && npm run prisma:generate && npm run build"
publish = ".next"

[build.environment]
PRISMA_CLI_BINARY_TARGETS = "linux-musl"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@prisma/client", "prisma"]
included_files = ["node_modules/.prisma/client/**"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
