backend:
  name: github
  repo: tumbleweird/tricitiesvote.com
  branch: '2023'

local_backend: true
media_folder: 'static/images'
public_folder: 'images'

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: candidates
    label: Candidates
    label_singular: Candidate
    slug: '{{year}}-{{name}}'
    folder: 'data/candidates'
    media_folder: '/{{media_folder}}/candidates'
    public_folder: '/{{public_folder}}/candidates'
    identifier_field: 'name'
    create: true
    extension: json
    fields:
      - { name: electionyear, label: Election year, default: '2023'}
      - { name: name, label: Name }
      - {
          name: office,
          label: Office title,
          widget: relation,
          collection: 'offices',
          required: false,
          multiple: false,
          searchFields: ['title'],
          valueField: 'title',
          displayFields: ['title'],
        }
      - { name: incumbent, label: 'Incumbent?', widget: boolean, required: false }
      - { name: yearsin, label: 'Years in office (if incumbent)', widget: number, required: false }
      - { name: image, label: Image, widget: image, required: false }
      - { name: bio, label: Short bio, widget: markdown, required: false }
      - { 
          name: party, 
          label: Political Party, 
          widget: select, 
          required: false,
          options:
            [
              { label: 'Democrat', value: 'Democrat' },
              { label: 'Republican', value: 'Republican' },
              { label: 'Libertarian', value: 'Libertarian' },
              { label: 'Independent', value: 'Independent' },
              { label: 'Non-Partisan', value: 'Non-Partisan' },
            ],
        }
      - { name: email, label: Email, required: false }
      - { name: statement, label: Statement, widget: markdown, required: false }
      - { name: website, label: Website, required: false }
      - { name: facebook, label: Facebook, required: false }
      - { name: twitter, label: Twitter, required: false }
      - { name: instagram, label: Instagram, required: false }
      - { name: youtube, label: YouTube, required: false }
      - { name: pdc, label: Campaign Finance, required: false }
      - { name: donors, label: Donors, widget: markdown, required: false }      
      - { name: lettersyes, label: Letters Yes / Endorsements, widget: markdown, required: false }
      - { name: lettersno, label: Letters No, widget: markdown, required: false }
      - { name: articles, label: Articles, widget: markdown, required: false }
      - { name: engagement, label: Engagement, widget: markdown, required: false }
      - { name: body, label: Body, widget: markdown, required: false }
      - { name: hide, label: 'Hide?', widget: boolean, required: false, default: false }
      - { name: minifiler, label: 'Minifiler?', widget: boolean, required: false, default: false }
      - { name: uuid, label: ID, hint: 'This is the state-assigned PDC filer_id.', hidden: true }
  - name: notes
    label: Candidate notes
    label_singular: Candidate notes
    slug: '{{title}}-notes'
    folder: 'data/notes'
    media_folder: '/{{media_folder}}/notes'
    public_folder: '/{{public_folder}}/notes'
    summary: "📓 {{title}} notes"
    create: true
    extension: json
    fields:
      - { 
        name: title, label: 'Candidate name', required: true
        }
      - {
          name: candidate,
          label: Candidate,
          widget: relation,
          multiple: false,
          collection: 'candidates',
          searchFields: ['name'],
          valueField: 'uuid',
          displayFields: ['name'],
        } 
      - { name: notes, label: Notes, widget: markdown, required: false, hint: 'This does not show up on the candidates page' }
      - { name: uuid, label: ID, widget: ncw-id }
  - name: offices
    label: Elected offices
    label_singular: Elected office
    identifier_field: title
    slug: '{{title}}'
    folder: 'data/offices'
    media_folder: '/{{media_folder}}/offices'
    public_folder: '/{{public_folder}}/offices'
    create: true
    extension: json
    fields:
      - { name: title, label: 'Full name of office', hint: 'Name of Region Name of Office Position (e.g. Franklin County Commissioner Pos 1 or Richland City Council Pos 4' }
      - {
          name: region,
          label: Region,
          widget: select,
          required: true,
          options:
            [
              { label: 'District 8', value: '8th District' },
              { label: 'District 9', value: '9th District' },
              { label: 'District 15', value: '15th District' },
              { label: 'District 16', value: '16th District' },
              { label: 'Benton County', value: 'Benton County' },
              { label: 'Franklin County', value: 'Franklin County' },
              { label: 'Benton-Franklin', value: 'Benton-Franklin' },
              { label: 'WA-4', value: 'WA-4' },
              { label: 'Kennewick', value: 'Kennewick' },
              { label: 'Pasco', value: 'Pasco' },
              { label: 'Richland', value: 'Richland' },
              { label: 'West Richland', value: 'West Richland' },
              { label: 'State', value: 'State' },
            ],
        }
      - {
          name: office,
          label: Office title,
          widget: select,
          required: true,
          options:
            [
              { label: 'City Council', value: 'City Council' },
              { label: 'School Board', value: 'School Board' },
              { label: 'Port Commissioner', value: 'Port Commissioner' },
              { label: 'County Commissioner', value: 'County Commissioner' },
              { label: 'WA Legislator (Senate)', value: 'WA Legislator (Senate)' },
              { label: 'WA Legislator (House)', value: 'WA Legislator (House)' },
              { label: 'Superior Court Judge', value: 'Superior Court Judge' },
              { label: 'U.S. House', value: 'U.S. House' },
              { label: 'U.S. Senate', value: 'U.S. Senate' },
              { label: 'Mayor', value: 'Mayor' },
              { label: 'Sheriff', value: 'Sheriff' },
              { label: 'Prosecutor', value: 'Prosecutor' },
            ],
        }
      - {
          name: job,
          label: Title of person holding office,
          widget: select,
          options:
            [
              { label: 'Council member', value: 'Council member' },
              { label: 'Board member', value: 'Board member' },
              { label: 'Commissioner', value: 'Commissioner' },
              { label: 'Representative', value: 'Representative' },
              { label: 'Senator', value: 'Senator' },
              { label: 'Judge', value: 'Judge' },
              { label: 'Mayor', value: 'Mayor' },
              { label: 'Sheriff', value: 'Sheriff' },
              { label: 'Prosecutor', value: 'Prosecutor' },
            ],
          required: true,
        }
      - { name: position, label: Position number, hint: 'If needed', widget: number, required: false }
      - { name: uuid, label: ID, widget: ncw-id }
  - name: races
    label: Election races
    label_singular: Election race
    slug: '{{electionyear}}-{{office}}'
    folder: 'data/races'
    media_folder: '/{{media_folder}}/races'
    public_folder: '/{{public_folder}}/races'
    summary: "{{electionyear}} {{office}} ({{type}})"
    create: true
    extension: json
    fields:
      - { name: electionyear, label: Election year, default: '2023'}
      - {
          name: office,
          label: Office title,
          widget: relation,
          collection: 'offices',
          required: true,
          searchFields: ['title'],
          valueField: 'title',
          displayFields: ['title'],
        }
      - { 
          name: type, 
          label: 'Election type', 
          widget: select, 
          multiple: false,
          options: [
            { label: 'Primary election', value: 'primary' },
            { label: 'General election', value: 'general' },
            { label: 'Special election', value: 'special' }
          ]
        }
      - {
          name: candidates,
          label: Candidates,
          widget: relation,
          multiple: true,
          collection: 'candidates',
          searchFields: ['name'],
          valueField: 'uuid',
          displayFields: ['name'],
        } 
      - { name: intro, label: Intro, widget: markdown, required: false, hint: 'Intro catch-all for content/links related to both/all candidates or the race in general.' }
      - { name: body, label: Body, widget: markdown, required: false, hint: 'Body catch-all for content/links related to both/all candidates or the race in general.' }
      - { name: hide, label: 'Hide?', widget: boolean, required: false, default: false }
      - { name: uuid, label: ID, widget: ncw-id }
  - name: guides
    label: Election guides
    label_singular: Election guide
    slug: '{{year}}-{{region}}'
    folder: 'data/guides'
    media_folder: '/{{media_folder}}/guides'
    public_folder: '/{{public_folder}}/guides'
    summary: "{{electionyear}} {{region}} {{type}} election"
    create: true
    extension: json
    fields:
      - { name: electionyear, label: Election year, default: '2023'}
      - {
          name: region,
          label: "Region",
          widget: select,
          multiple: false,
          required: true,
          options:
            [
              { label: 'Benton County', value: 'Benton County' },
              { label: 'Franklin County', value: 'Franklin County' },
              { label: 'Kennewick', value: 'Kennewick' },
              { label: 'Pasco', value: 'Pasco' },
              { label: 'Richland', value: 'Richland' },
              { label: 'West Richland', value: 'West Richland' },
            ],
        }
      - { 
          name: type, 
          label: 'Election type', 
          widget: select, 
          multiple: false,
          options: [
            { label: 'Primary election', value: 'primary' },
            { label: 'General election', value: 'general' },
            { label: 'Special election', value: 'special' }
          ]
        }
      - {
        name: races,
        label: Election races,
        required: true,
        widget: relation,
        collection: 'races',
        multiple: true,
        searchFields: ['electionyear', 'office', 'type'],
        valueField: 'uuid',
        displayFields: ['electionyear', 'office', 'type'],
        }
  - name: endorsements
    label: Endorsements
    label_singular: Endorsement
    slug: '{{endorser}}-{{forAgainst}}-{{candidate}}'
    folder: 'data/endorsements'
    media_folder: '/{{media_folder}}/endorsements'
    public_folder: '/{{public_folder}}/endorsements'
    summary: "{{endorser}} {{forAgainst}} {{candidate}}"
    create: true
    extension: json
    fields:
      - {
        name: candidate,
        label: Candidate,
        widget: relation,
        multiple: false,
        collection: 'candidates',
        searchFields: ['name'],
        valueField: 'uuid',
        displayFields: ['name'],
        } 
      - { name: endorser, label: Endorser, required: true}
      - { name: url, label: Url, required: true}
      - { 
        name: type, 
        label: 'Type', 
        widget: select, 
        multiple: false,
        options: [
          { label: 'Letter to the editor', value: 'letter' },
          { label: 'Social media post', value: 'social' },
          { label: 'Organization', value: 'org' },
        ]
      }
      - { 
          name: forAgainst, 
          label: 'For or against?', 
          widget: select, 
          multiple: false,
          options: [
            { label: 'For', value: 'for' },
            { label: 'Against', value: 'against' }
          ]
        }